### ISSUE TITLE
Images in RedistrictingProgram.md use colors indistinguishable when printed in monochrome

### ISSUE THREAD

**Issue by jody** [MetroCS/redistricting#104]
**Describe the bug**
When printed on a monochrome printer (e.g., B&W laser printer) the locations in the grid of the current version of [RedistrictingProgram.md](https://github.com/MetroCS/redistricting/blob/master/RedistrictingProgram.md) are indistinguishable. That is, they all render as the same shade of grey.

As a temporary "fix" for this problem, suggest reverting images in RedistrictingProgram.md to those found in OldRedistricting.md

_Originally posted by @jody in https://github.com/MetroCS/redistricting/issues/88#issuecomment-964576216_

**To Reproduce**
1. Print RedistrictingProgram.md to a monochrome printer
2. Note that the locations in the grid are all shown as the same shade of gray

**Expected behavior**
When the RedistrictingProgram.md file is printed, whether using a color or monochrome printer, the fill colors of grid squares that represent part affiliation in images are distinguishable.

**Additional context**
Images in [OldRedistricting.md](https://github.com/MetroCS/redistricting/blob/master/OldRedistricting.md) do not exhibit this problem. Unfortunately, the images in OldRedistrricting.md do not show district boundaries as clearly.

**Comment by am10nxw** [comment]
Can I take this one.

**Comment by jody** [comment]
Have at it!
