### ISSUE TITLE
[UserStory] Error Handling through inputs

### ISSUE THREAD

**Issue by wavypng** [MetroCS/redistricting#111]
# User Story
### Essential components

- [ ] Stakeholder 
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story 
**As a**  stakeholder (End User)

I want the application to print an error that you need to input the appropriate character type, in this instance an int type. **so that**  the user doesn't assume what variable type to input.  Fixing error handling through inputs. 

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Rule 1_ The program gives an output telling the user that their input is incorrect and to retry with the right variable.

## Dependencies
N/A

**Comment by jody** [comment]
Since this is a utility library, there is no single "program" per se.
Please be more specific.

**Comment by jody** [comment]
Removing RedistrictingDriver from the package is becoming a highly likely outcome. All issues/PRs that address concerns involving RedistrictingDriver are thus likely to be irrelevant. Am putting all such activity "on hold" for now.

**Comment by jody** [comment]
* See #145
