### ISSUE TITLE
[UserStory] Update tests in DistrictTest.java, LocationTest.java, and PartyTest.java to use JUnit 5 Jupiter as partial solution to issue #58

### ISSUE THREAD

**Issue by am10nxw** [MetroCS/redistricting#114]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _maintainer_ 
**I want**  _all tests in the files [DistrictTest.Java](https://github.com/MetroCS/redistricting/blob/e146aca06033eddca11766090d3aef0723f06b64/src/swdmt/redistricting/DistrictTest.java), [LocationTest.java](https://github.com/MetroCS/redistricting/blob/e146aca06033eddca11766090d3aef0723f06b64/src/swdmt/redistricting/Location.java), and [PartyTest.java](https://github.com/MetroCS/redistricting/blob/e146aca06033eddca11766090d3aef0723f06b64/src/swdmt/redistricting/PartyTest.java) to use the JUnit 5 Jupiter API_ 
**so that**  _unit testing is consistent with JUnit 5 and legacy JUnit4 support is no longer needed._

This is a necessary component of User Story #58, which has been marked as an epic.

## Acceptance Criteria
* Each of the following files uses JUnit 5 Jupiter imports and no JUnit 4 legacy imports:
  * [DistrictTest.Java](https://github.com/MetroCS/redistricting/blob/e146aca06033eddca11766090d3aef0723f06b64/src/swdmt/redistricting/DistrictTest.java)
  * [LocationTest.java](https://github.com/MetroCS/redistricting/blob/e146aca06033eddca11766090d3aef0723f06b64/src/swdmt/redistricting/Location.java)
  * [PartyTest.java](https://github.com/MetroCS/redistricting/blob/e146aca06033eddca11766090d3aef0723f06b64/src/swdmt/redistricting/PartyTest.java)
* Each of the following files are written according the JUnit 5 Jupiter API.
  * [DistrictTest.Java](https://github.com/MetroCS/redistricting/blob/e146aca06033eddca11766090d3aef0723f06b64/src/swdmt/redistricting/DistrictTest.java)
  * [LocationTest.java](https://github.com/MetroCS/redistricting/blob/e146aca06033eddca11766090d3aef0723f06b64/src/swdmt/redistricting/Location.java)
  * [PartyTest.java](https://github.com/MetroCS/redistricting/blob/e146aca06033eddca11766090d3aef0723f06b64/src/swdmt/redistricting/PartyTest.java)

## Supporting Information
See: [JUnit.org](https://junit.org)
See: [Hamcrest.org](http://hamcrest.org/JavaHamcrest/index)
Epic: #58 

### Dependents
#58

**Comment by jody** [comment]
Title doesn't indicate the intent of the updating.
Outcome appears to be circular.
Acceptance criteria has errors. (It is better to link directly to the files than enter potentially incorrect filenames.)

Supporting information doesn't explain why these three files in particular warrant updating.

Please update this user story.

**Comment by am10nxw** [comment]
Hopefully this makes sense. Let me know if I need make any more changes.
