### ISSUE TITLE
[UserStory] Add a test class for the StarGenerator.java class.

### ISSUE THREAD

**Issue by mmeraz6** [MetroCS/redistricting#129]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _maintainer_  
**I want**  _a test class for the StarGenerator.java class_  
**so that**  _the class is tested and test coverage of the class is effective_

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _The class `StarGeneratorTest` exists_
* _All public methods in StarGenerator have corresponding tests_

## Supporting Information
At present there is only one public method:
https://github.com/MetroCS/redistricting/blob/d93df23834d9f120e2295ce7ac404565cbd13558/src/swdmt/redistricting/StarGenerator.java#L16-L21

**Comment by 13Lena** [comment]
[2:40 PM] Johnson, Malcolm
copy paste this:Created an incomplete test class as a starting place, testing the following things:- The number of `Location` objects in each pattern is equivalent to some desired input `n`
- Each pattern is contiguous
- Each Location is unique within a particular patternWe suggest breaking up `generatePatternTest` method into private methods that test each of the above assertions individually. Even though the basics of the tests are here, it possible more components for the test class are needed.

**Comment by jarell38** [comment]
i would like to be assigned to this issue

**Comment by rjbeer** [comment]
@jody could you assign me to this problem. I am working with jarell38, and colinlouis95 on this issue.

**Comment by jody** [comment]
Assignments done. (Note that I can only assign this issue to those who have entered a comment on this issue.)

**Comment by ColinLouis95** [comment]
Hello Jody, i would also like to be assigned to this issue
