### ISSUE TITLE
[UserStory] No getter function for this.voterMap in Region.java

### ISSUE THREAD

**Issue by millerac38** [MetroCS/redistricting#135]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  maintainer
**I want**  a getter for this.voterMap in Region.java
**so that**  we can use it for unit testing.

## Supporting Information
this.voterMap should be accessible with a getter. As of right now, you can't run tests on it to ensure functionality.

**Comment by jody** [comment]
Our general philosophy is that **private** data and methods should not be made public simply for the purposes of test. That potentially violates the meaning and intent of visibility specifiers.
