### ISSUE TITLE
[UserStory] correcting the vision statement Readme.md for Redistricting

### ISSUE THREAD

**Issue by Cmeek09** [MetroCS/redistricting#137]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a stakeholder
I want the vision of Redistricting to more correlate with its trajectory.  It is no longer accurate to describe it as a application, but more accurate to say this is a library to which a application could incorporate at some point.  
So that we minimize confusion and others to contribute are on the same page.   

## Acceptance Criteria
The edited document should change the language to express that Redistricting is not going to be application, but rather a tool that can be used in a application.  A library is a more accurate description of this project now.

## Supporting Information
It does mention more in the vision.md file that scope is to create "A library (Java package) that provides utilities for building programs that investigate redistricting scenarios".  So again, just to align everyone efforts on this and have a concise vision and goal for this project.

**Comment by jody** [comment]
This appears to have already been addressed.
Please review [README.md](https://github.com/MetroCS/redistricting/blob/b7ad2e28a71f2f65738233ea5c4f778bc35d2ff6/README.md) and resubmit with specifics if necessary.
