### ISSUE TITLE
[UserStory] Addition of Wiki Page to Repository Containing Documentation

### ISSUE THREAD

**Issue by cjens00** [MetroCS/redistricting#138]
# User Story
### Essential components
- [ x] Title describes the story
- [ x] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _potential user of redistricting_  
**I want**  _to click the Wiki button and see a modern API documentation wiki_  
**so that**  _the project does not rely solely on code reading to understand._

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Rule 1_

_**Scenario 1**_  
**Given**  _initial state or conditions_  
**when**  _event or action_  
**then**  _specified outcome_  

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by jody** [comment]
Incomplete issue specification.

Also needs explanation of the meaning of a "modern API documentation Wiki".

Please review the [redistricting API](https://metrocs.github.io/redistricting/api/index.html) to see if this is addresses the intent.
