### ISSUE TITLE
Add test for AllDistictGen

### ISSUE THREAD

**Issue by 13Lena** [MetroCS/redistricting#139]
# User Story
### Essential components
- [ ] Title describes the story
- [x] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story

As a maintainer I want a test added for the AllDistrictGen class. There is no test currently.

## Acceptance Criteria

A new test class named AllDistrictGenTest that creates tests for the AllDistrictGen class. This class should test both the public classes in AllDistrictGen. 
Does ArrayList<District> generateDistricts create legal districts?

## Supporting Information
There are two public classes to test in AllDistrictGen

![Screenshot from 2021-12-02 14-21-26](https://user-images.githubusercontent.com/46757429/144505273-76c6d3cc-828d-425f-9b11-246a631bd88f.png)

**Comment by jody** [comment]
Please use the User Story template.

The acceptance criteria statement is confusing.
- Are there subclasses within AllDistrictGen?
- What is the intent of the question, "Does ArrayList generateDistricts create legal districts?"

**Comment by jody** [comment]
Incomplete. No response in 15 days. Closing issue.
