### ISSUE TITLE
[UserStory] Clean up Archive

### ISSUE THREAD

**Issue by jody** [MetroCS/redistricting#176]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _maintainer_  
**I want**  _files in the Archive directory pruned_  
**so that**  _only files with current relevance appear_

## Acceptance Criteria

* Files no longer relevant have been deleted, including
  * _[NewRedistricting.md](https://github.com/MetroCS/redistricting/blob/c7c6f18ef19d51ab3f3b5044e76364b2e7ca53d0/Archive/NewRedistricting.md)_
  * _[OldRedistricting.md](https://github.com/MetroCS/redistricting/blob/c7c6f18ef19d51ab3f3b5044e76364b2e7ca53d0/Archive/OldRedistricting.md)_

## Supporting Information
The current version, _[Redistricting.md](https://github.com/MetroCS/redistricting/blob/main/Redistricting.md), is stable obviating the need for contemporaneous reference to its precursors._

### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by rjbeer** [comment]
@jody could you assign this issue to me?
