### ISSUE TITLE
StarGenerator.java class should be renamed

### ISSUE THREAD

**Issue by noah-fullerton** [MetroCS/redistricting#192]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [ ] Outcome is described
- [x] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _maintainer_
**I want**  _StarGenerator.java to have a class name that better represents its function_  
**so that**  _class function is more easily understood_

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

- [ ] Class is appropriately named so it is easy to discern intended functionality when called externally.
- [ ] Class name should refer to the fact that it generates a collection of patterns 

## Supporting Information
_(Relevant information, context, resources)_

-  When class is called in [AllDistrictGen.java ](https://github.com/MetroCS/redistricting/blob/dacf6fd20624a4dcd720afce5516a5d3201f0f99/src/metrocs/redistricting/AllDistrictGen.java#L25-L26) , term "Star Generator" provides no value. 
`     ArrayList<ArrayList<Location>> starPattern =
                                   StarGenerator.generatePattern(districtSize);`
This ambiguity leads maintainers to wonder what is going on. A better name for the class would make this line more clear.

- StarGenerator.java is a utility class with a single function, generatePattern. The class name should communicate this function in someway.  [StarGenerator.java](https://github.com/MetroCS/redistricting/blob/dacf6fd20624a4dcd720afce5516a5d3201f0f99/src/metrocs/redistricting/StarGenerator.java#L20)

### Dependents
- https://github.com/MetroCS/redistricting/issues/129#issue-1069003401
_(Issues dependent on this story)_

**Comment by jody** [comment]
How is "appropriately named" to be measured so that we know if the solution satisfies this user story?

**Comment by noah-fullerton** [comment]
Would changing this acceptance criteria to the following be more measurable?

> Class name is descriptive, simple, and answers the question: "what exactly does this class do?"

**Comment by jody** [comment]
Consider the assertion that StarGenerator is a valid and appropriate name because "the class contains methods that generate alternative collections of locations formed by pushing out in all directions from a specified origin in a star-like pattern."

Note that the StarGenerator class itself isn't invoked. It contains methods that are invoked to perform specific behaviors. This utility class may house numerous methods (but not a constructor method).

**Comment by jody** [comment]
No response in over 30 days.
