### ISSUE TITLE
[UserStory] Contributing.md link from the readme.md should be a subpoint for clarity

### ISSUE THREAD

**Issue by AragornIISOA** [MetroCS/redistricting#193]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _User, Maintainer_  
**I want**  _The contributing section of the readme to be more clear_  
**so that**  _when we're looking for information on contributing, tools, and technologies, it's simpler_

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Rule 1: Clearly communicate that contributing.md contains information on Contributing, Technologies, and Tools_

_**Scenario 1**_  
**Given**  _the contributing link is more clear_  
**when**  _someone is looking for information on tools and technologies as well_  
**then**  _such a person would be able to find what they're looking for easier_  

## Supporting Information
_The information found in the Contributing.md section also tells users/maintainers what technologies and tools are used._
_This is related to_
- #4 

### Dependents

**Comment by jody** [comment]
How are we to measure "more clear" in order to determine whether this user story is satisfied by a solution?

**Comment by AragornIISOA** [comment]
Suggested Change: Under the 'I Want' section of the 'Story' section, It could be updated to say
"I want...the readme to clearly communicate that contributing.md contains information on Contributing, Technologies, and Tools and to have access to the contributing.md in a prominent place in said readme."
Suggested Change 2: Under the Acceptance Criteria, add Rule 2: "Contributing.md is in a prominent place, easily accessible to newcomers.

**Comment by jody** [comment]
Would this issue be satisfied by simply moving the last sub-bullet from the current [README](https://github.com/MetroCS/redistricting#readme) into the [Contributing](https://github.com/MetroCS/redistricting/blob/main/Contributing.md) document?

Here are quick mock-ups showing the README without the confusing extra sub-bullet and the Contributing document with a link to the conventions document.
___

README.md
<img width="1319" alt="Screen Shot 2022-05-04 at 5 41 40 PM" src="https://user-images.githubusercontent.com/379845/166842407-245fa257-0d76-41fc-acf1-05f30ae2f202.png">
___

Contributing.md
<img width="1524" alt="Screen Shot 2022-05-04 at 5 47 25 PM" src="https://user-images.githubusercontent.com/379845/166842805-31e4918e-c8a3-476e-9171-284997710aa3.png">
