### ISSUE TITLE
[UserStory] Split readMe into separate documentation  

### ISSUE THREAD

**Issue by zmorlan1** [MetroCS/redistricting#20]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  User 
**I want**  the readMe split into separate documents  
**so that**  information is less clustered and clear to find

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* create separate files for definitions of Region, District, Favored Party and Gerrymandering
* link documents, including vision, to readMe for easy access for information  
* keep key information to project such as title, objective and project information in ReadMe

_**Scenario 1**_  
**Given** current readMe is clustered with project information 
**when**  information is separated and linked to different files
**then** the readMe will be clearer to navigate to find appropriate information  

## Supporting Information
_(Relevant information, context, resources)_
build off of change clustered ReadMe.md (#11 )
### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by jody** [comment]
Why is this a "student" concern?
(Without defined stakeholders, it is difficult to understand this User Story.)

**Comment by zmorlan1** [comment]
changed the stakeholder type from student.

**Comment by mykewlker** [comment]
Please assign this user story to myself. I would like to update the supporting information and dependencies

**Comment by zmorlan1** [comment]
User Story has been added into epic User Story
