### ISSUE TITLE
Complete TODO in allDistrictsOfSpecificSize(); in Redistrictor.java

### ISSUE THREAD

**Issue by Jessica-Trujillo** [MetroCS/redistricting#21]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  User  
**I want**  the TODO in allDistrictsOfSpecificSize() in Redistrictor.java to be completed 
**so that**  the program works for districts of size greater than one.

## Acceptance Criteria
The product correctly addresses districts of size greater than 1 

_**Scenario 1**_  
**Given**  the districtSize > 1  
**when**  the program is run
**then**  all possible districts will be calculated within region

## Supporting Information
Refer to Redistrictor.java method allDistrictsOfSpecificSize();

### Depends On
N/A
### Dependents
N/A

**Comment by Jessica-Trujillo** [comment]
Please assign to Fred

**Comment by Jessica-Trujillo** [comment]
Please assign me to this issue.
Thanks!

**Comment by mykewlker** [comment]
This issue has been resolved and updated to the master. Please let us know if there are any additional items or if this can be closed

**Comment by jody** [comment]
Accepted.  See related Checkstyle issues #30 and #31
