### ISSUE TITLE
[UserStory] What are the coding conventions and styles for this project?

### ISSUE THREAD

**Issue by mykewlker** [MetroCS/redistricting#27]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _Developer_  
**I want**  _to know the accepted formats of the code currently within this project_  
**so that**  _additional code can be implemented in a similar fashion_

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _A reference of styles currently in use in the program_
* _A rule guide showing what is acceptable in checkstyles and formats_
* _Exceptions from listed rule guides that is relevant to the project _

## Supporting Information
Current developmental conventions list Sun and Google as guides but offer no examples of how these have been implemented into the project. Guides aren't identical so which style are we using vs another? 
    Sun Convention guide: https://www.oracle.com/technetwork/java/codeconvtoc-136057.html
    Google Convention guide: https://google.github.io/styleguide/javaguide.html

## Dependencies
[User Story](https://github.com/MetroCS/redistricting/issues/4)

**Comment by jody** [comment]
The [Coding Convention Guide](../blob/master/DevelopmentConventions.md#Coding-Convention-Guide) resolves when each guide is used.  In particular,
* _project-specific_ guidelines are always used.

For situations not covered by the project-specific guide,
* the _Sun Convention_ guide is used.

If neither of these apply, then
* the _Google Convention_ guide is used.

It also describes adding new conventions not appearing in _any_ of those guides.

Clarification is needed to understand what is intended by each of the following:
* reference of styles  _(what is needed beyond the three listed guides)_
* rule guide  _(???)_
* exceptions  _(what exceptions wouldn't just appear within the project-specific guidelines))_

**Comment by mykewlker** [comment]
Closing this issue to be better defined within an additional user issue.
