### ISSUE TITLE
[UserStory] Add unit tests to Redistrictor.java and Region.java to catch size parameter exceptions

### ISSUE THREAD

**Issue by mykewlker** [MetroCS/redistricting#28]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _developer_  
**I want**  _JUnit tests that address parameters that reflect invalid sizes for a constructed region_  
**so that**  _regression tests will validate appropriate exception handling for invalid size parameters_

## Acceptance Criteria
* Unit tests verify size parameter validation in the product
* Unit tests verify that parameters that would result in invalid region sizes result in exceptions being thrown

### Depends On
#68 #69 (#35)

## Supporting Information
[JUnit5 - Assertions.assertThrows](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html#assertThrows(java.lang.Class,org.junit.jupiter.api.function.Executable))

**Comment by mykewlker** [comment]
Please assign to @Jessica-Trujillo @FrederickBuker @zmorlan1

**Comment by jody** [comment]
Title, outcome, and acceptance crtieria are too vague.  This is a "super epic" that would never be completed.

Consider scoping this down to some specific area that needs additional tests.

Also, since we are using JUnit5, the preferred way of testing for exceptions is through use of the [org.junit.jupiter.api.Assertions.assertThrows()](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html#assertThrows(java.lang.Class,org.junit.jupiter.api.function.Executable)) method.

**Comment by mykewlker** [comment]
Title and acceptance criteria has been updated on this story in an effort to broaden the scope of the story

**Comment by jody** [comment]
Outcome doesn't match the Title.  Outcome can be more specific, but not less specific, than the Title.  The Outcome must be able to stand on its own, without reference to the Title.

Acceptance Criteria likewise doesn't match the Title.  Acceptance Criteria can be more specific, but not less specific, than the Title.  The Acceptance Criteria must be able to stand on their own, without reference to the Title or Outcome.

**Comment by TheGerbilvonSteuben** [comment]
Last Minute Software Solutions would like to handle this issue

**Comment by jody** [comment]
**N.B.** This issue is labeled "incomplete info" and "outcome", "rationale", and "acceptance criteria" are not validated.  Initial effort needs to address the issue shortcomings.

**Comment by TheWillN** [comment]
This issue #28 seems to have been addressed more clearly in issues #68 and #69.  Last Minute Software Solutions suggests that this issued be closed.

**Comment by jody** [comment]
Thank you for the observation!
This appears to be an epic.
#68, #69, and potentially #35 are dependencies.
I will update the body of the issue to reflect the current meaning and status.

**Comment by jody** [comment]
All dependent subtasks completed.
