### ISSUE TITLE
Description bug in Redistrictor.java

### ISSUE THREAD

**Issue by FrederickBuker** [MetroCS/redistricting#29]
**Describe the bug**
The description for allDistrictsOfSpecificSize is asking for a ±1 of a district. This is not needed due to the fact that all this method should do is find all the possible districts in the specified region.

**To Reproduce**
1. Go to 'redistrictor.java lines 90-100'

**Expected behavior**
The description should only be to create any and all possible districts for a specified region.

**Comment by barismutan** [comment]
Hello, can I work on this issue?

**Comment by jody** [comment]
Anyone can work on any issues they wish to at any time.  🙂

What is your specific request?

**Comment by barismutan** [comment]
Hello, sorry I had midterms; The project is very interesting and I would like to see if I can help by any means. I submitted a pull request for this issue. I apologize if I skipped some step with regards to specifying the issue for the pull request, as it is my first time contributing to an open source project. I really appreciate your feedback.
