### ISSUE TITLE
[UserStory] Update build and tests to JUnit 5

### ISSUE THREAD

**Issue by jody** [MetroCS/redistricting#58]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _maintainer_  
**I want**  _JUnit framework updated to JUnit 5_  
**so that**  _all testing is consistent with JUnit 5 and no legacy (JUnit4) is needed to be supported._

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* Build process does not invoke legacy JUnit 4 framework
* All test classes and tests are consistent with JUnit 5

## Supporting Information
See: [JUnit.org](https://junit.org)
See: [Hamcrest.org](http://hamcrest.org/JavaHamcrest/)

### Depends On
- #114
- #115
- #116 
- #117 
- #118

**Comment by JA2016** [comment]
Can I be added assigned to this issue

**Comment by ismailali999** [comment]
Hi, can you please add me am interested

**Comment by AshishAcharya0000** [comment]
I would like to claim this issue.

**Comment by AshishAcharya0000** [comment]
Dreamwork Technologies would like to claim this issue.

**Comment by flip1012** [comment]
We are working on the issue, we are currently working on making it run without any issues so that we can start updating the build and files.

**Comment by flip1012** [comment]
We have sadly over estimated our abilities to approach this issue, and we would like to give up this issue to another group.

**Comment by jody** [comment]
All dependent subtasks completed.

**N.B.** An outcome of satisfying this user story is the creation of a new high priority issue, _loss of test coverage assessment:_
- #141
