### ISSUE TITLE
[UserStory] Provide constructor:  Region(java.util.Collection<Voter> voters)

### ISSUE THREAD

**Issue by jody** [MetroCS/redistricting#59]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _user_  
**I want**  _the Region class to have constructor `Region(<java.util.Collection<Voter> voters)`_  
**so that**  _my programs can create regions based on a given collection of Voter objects._

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* Invoking the constructor returns a new Region object that references the Voter objects given as a parameter and the Locations associated with those Voter objects.

* See "Additional Design Decisions Needed"

## Additional Design Decisions Needed
* What behavior should the constructor exhibit when a Voter object has no Location (e.g., the `location()` method returns _null_). Should that Voter object be ignored?  Should an exception be thrown?
* What behavior should the constructor exhibit when more than one Voter object has the same Location value (i.e., the `location()` method returns Location objects that are `equal`). Should an exception be thrown? Should an arbitrary Voter be associated with that Location and all others be ignored?

### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by bansheep** [comment]
Me (Jess) and BBautista22 are working on this!

**Comment by jody** [comment]
It appears that GitHub only permits me to make assignments to someone who has commented on the issue.  Thus **each person who wants to be assigned an issue must make the request in a comment to the issue**.

Reference: https://help.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users

**Comment by BBautista22** [comment]
Request to be added to this issue

**Comment by HuyBui-ruum** [comment]
DreamWork Technologies would like to claim this issue.

**Comment by jody** [comment]
Note the design decisions that need resolution (section: _Additional Design Decisions Needed_).

**Comment by flip1012** [comment]
We are testing what we wrote, we should be ready to make a pull request in the next couple of days.

**Comment by flip1012** [comment]
Testing is done, we are hoping to create a pull request within the next 2 days

**Comment by flip1012** [comment]
We ended up deleting our previous fork and ended up starting from scratch, but this will not affect the previous pull request schedule we have. In fact we feel as though this will in fact speed it up.

**Comment by jody** [comment]
No PR as expected 5 days ago. Returning to To Do status to open contributions.  Feel free to issue PR when ready.
