### ISSUE TITLE
contiguityValid() method failing with districts in a region greater than 2x2. 

### ISSUE THREAD

**Issue by Estrada303** [MetroCS/redistricting#60]
**Describe the bug**
When a region that is bigger than 2x2 is used. The contiguityValid() method returns true when the districts that are being passed to the method are not contiguous.  

**To Reproduce**

1. Create a district that is non-contiguous 
district locations = {(1,0),(2,0),(0,1),(0,2)}

2. Pass this district to contiguityValid() method.

test used:

@Test
    public void contiguityValidDistrictNotSquare() {
            HashSet<Location> locations = new HashSet<>();
            locations.add(new Location(1,0));
            locations.add(new Location(2,0));
            locations.add(new Location(0,1));
            locations.add(new Location(0,2));
            District district1 = new District(locations);
            assertFalse(district1.contiguityValid());
    }

**Expected behavior**
The method should return false when a district with locations {(1,0),(2,0),(0,1),(0,2)} is passed to it.

**Screenshots**

**Desktop (please complete the following information):**
 - Micorsoft Windows 10
 - JDK 14.0.1

**Comment by Estrada303** [comment]
@jody Once this bug is triaged can I get it assigned to me.

**Comment by jody** [comment]
Good inclusion of steps to reproduce!

Suggestions for the future:
When filing this kind of bug report, think about what would be helpful to some new maintainer (other than yourself).  Perhaps provide more context, such as what class the method is in, by using a specific reference link:
[District.continguityValid](../blob/20c1959fba6119fb6e95d30e283ae01fb4e39caf/src/swdmt/redistricting/District.java#L51-L71)
Likewise for where the test code should reside, such as [DistrictTest.contiguityInvalidNonemptyDistrictTest](https://github.com/MetroCS/redistricting/blob/20c1959fba6119fb6e95d30e283ae01fb4e39caf/src/swdmt/redistricting/DistrictTest.java#L70) or as a new method in the [DistrictTest](https://github.com/MetroCS/redistricting/blob/20c1959fba6119fb6e95d30e283ae01fb4e39caf/src/swdmt/redistricting/DistrictTest.java) class.

Assigning this issue to @Estrada303
