### ISSUE TITLE
Broken Build - District.java compilation errors

### ISSUE THREAD

**Issue by jody** [MetroCS/redistricting#64]
**Compilation error in build**
BUILD FAILED
edistricting/build.xml:131: Compile failed; see the compiler error output for details.

```
compile:
    [javac] Compiling 18 source files to redistricting/build/classes
    [javac] redistricting/src/swdmt/redistricting/District.java:59: error: cannot find symbol
    [javac]                    Set<Location> contiguousLocations = new HashSet<>();
    [javac]                                                            ^
    [javac]   symbol:   class HashSet
    [javac]   location: class District
    [javac] redistricting/src/swdmt/redistricting/District.java:60: error: cannot find symbol
    [javac]                    Set<Location> filterdLoc = new HashSet<>();
    [javac]                                                   ^
    [javac]   symbol:   class HashSet
    [javac]   location: class District
    [javac] 2 errors
```
**To Reproduce**
1. Issue command `ant clean compile`

**Expected behavior**
No compilation error.

**Recommendation**
Revert changes from `HashSet` back to `TreeSet` so that the ordering of Location objects is preserved in the Set collections.  (Could find no explanation for why `TreeSet` was replaced by `HashSet`.)

**Build environment**
 - JDK: 1.8.0_121 and OpenJDK 11.0.6+10
 - Ant 1.10.7
 - OS: OS X 10.15.4

**Comment by TheGerbilvonSteuben** [comment]
My team would like to claim this issue.
