### ISSUE TITLE
[UserStory] Create a JUnit test for the Region.java initialization parameter exception.

### ISSUE THREAD

**Issue by MckinnlyIngleby** [MetroCS/redistricting#68]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _developer_  
**I want**  _a JUnit test that verifies an appropriate exception is thrown when not using a perfect square as the parameter of the [`Region(int)` constructor](https://github.com/MetroCS/redistricting/blob/d022764cba3f008981a08c2cedc0b2771548a6d6/src/swdmt/redistricting/Region.java#L51-L59)_  
**so that**  _the implementation code is tested_

## Acceptance Criteria
* A JUnit test exists that expects an IllegalArgumentException when the parameter of the `Region(int)` constructor is not a perfect square.

_**Scenario 1**_
**Given**  _a unit test exists that passes 3 as the parameter to the Region constructor, `new Region(3)`, and specifies the expectation of an IllegalArgumentException_  
**when**  _that unit test is executed_
**then**  _the test reports no errors._

### Dependents
_issue #28_

**Comment by jody** [comment]
I've edited the story to fix formatting of the outcome and to clarify that this is in reference to the specific constructor method [Region(int)](https://github.com/MetroCS/redistricting/blob/d022764cba3f008981a08c2cedc0b2771548a6d6/src/swdmt/redistricting/Region.java#L51-L59).   Also adjusted the scenario to be presented in terms of the desired test outcome.

**Comment by NickLM1200** [comment]
Team Explorers will be working on this issue.

**Comment by jody** [comment]
> Team Explorers will be working on this issue.

Sounds good. Since it's E:1 what is your expected completion time/date?
