### ISSUE TITLE
[UserStory] Create JUnit Test for Redistrictor.java IllegalArgumentException

### ISSUE THREAD

**Issue by TheWillN** [MetroCS/redistricting#69]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  Developer   
**I want**  a JUnit test that ensures an exception is thrown when null region is used in Redistrictor.
**so that**  code is tested to verify values.

## Acceptance Criteria
Write a test that anticipates an IllegalArgumentException when theRegion is null.  

_**Scenario 1**_  
**Given**  A unit test Redistrictor verifying exception throw.
**when**  the theRegion has a value of null
**then**  receive IllegalArgumentException

## Reference
##Reference
    https://github.com/MetroCS/redistricting/blob/d022764cba3f008981a08c2cedc0b2771548a6d6/src/swdmt/redistricting/Redistrictor.java#L30-L42

**Comment by KyleKing54** [comment]
Team CRIT would like to work on this issue.

**Comment by jody** [comment]
All are free to work on this. Given that it is estimated as E1, it is expected to result in a PR during a single working session.

**Comment by ylATeRTyl** [comment]
I believe this issue is closed. Lines 41-44 in RedistrictorTest.java

**Comment by jody** [comment]
Thanks for the investigation and info!

Note that it's useful to actually link to the lines using GitHub markdown; for example
https://github.com/MetroCS/redistricting/blob/5323c65c3ed2e20f6633b99b7eb6850621b56ec2/src/swdmt/redistricting/RedistrictorTest.java#L41-L44

It appears that this issue (#69) is a part of epic issue #28. Noting this here for reference.
