### ISSUE TITLE
Update Build.xml to run Jar

### ISSUE THREAD

**Issue by mykewlker** [MetroCS/redistricting#8]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  Developer
**I want**  the build.xml to automatically run the jar file created from the build
**so that**  we can automatically run redistricting

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_
 
`build.xml` file updated so that when you perform "`ant run`" the appropriate jar file is created and executed.

**Comment by jody** [comment]
A key problem with this (and all user stories except #1) is that there are no stakeholder types identified for the project.  So user story #1 needs to be addressed before any other user stories can make sense.

**Comment by jody** [comment]
The rationale also doesn't provide more than a restatement of the outcome.  What's missing is _why_ the developer wants to automatically run redistricting via Ant.

**Comment by jody** [comment]
See offline comments (via e-mail).

**Comment by mykewlker** [comment]
Please assign to @Jessica-Trujillo and @FrederickBuker as well

**Comment by mykewlker** [comment]
User story updated to reflect more applicable acceptance criteria. At this time this issue looks to be completed
