### ISSUE TITLE
Input prompts not showing when running the demo using ant

### ISSUE THREAD

**Issue by thrandale** [MetroCS/redistricting#87]
**Describe the bug**
When running the demo using ant, the input prompts do not show in the command line till after you give it the inputs

**To Reproduce**
1. Run the demo using "ant run"
2. Enter three values (i.e. 3, 3, 3) separated by a new line
3. Does not show the prompts until after you give it the inputs

**Expected behavior**
The terminal should produce a prompt for the expected input
1. Please enter the number of rows
2. Please enter the number of columns
3. Please enter the number of districts Size

**Desktop :**
 - OS: Windows, MacOS, and Ubuntu

**Additional context**
If you run the jar file directly opposed to running with ant, it produces the expected results.

**Comment by jody** [comment]
Given that there's no specification for the demonstration prototype, and that the code works when run directly, this doesn't appear to be a "bug".

Perhaps this is more of a "User Story" from the perspective of maintainers indicating tool configuration changes.
