### ISSUE TITLE
[UserStory] Improve greyscale rendering of Redistricting Program description images

### ISSUE THREAD

**Issue by jody** [MetroCS/redistricting#88]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _user_, an _educator_, and a _developer_  
**I want**  _the images in the [Redistricting Program description document](https://github.com/MetroCS/redistricting/blob/master/RedistrictingProgram.md) to provide greater distinction when viewed in greyscale_  
**so that**  _the meaning of the content is readily apparent without requiring the ability to distinguish colors._

## Acceptance Criteria

_**Scenario 1**_  
**Given**  _the [Redistricting Program](https://github.com/MetroCS/redistricting/blob/master/RedistrictingProgram.md) document is being viewed in greyscale or printed on a greyscale printer_
**when**  _the resulting renderings of included images are viewed_  
**then**  _at least 80% of people asked to review the images report the party association of locations are well-distinguished and the district boundaries associated with party preferences are well-distinguished._  

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
User Story #104
### Dependents
_(Issues dependent on this story)_

**Comment by jody** [comment]
When printed on a monochrome printer (e.g., B&W laser printer) the locations in the grid of the current version of RedistrictingProgram.md are indistinguishable; that is, all the same shade of grey.

As a temporary "fix" for this problem, suggest reverting images in RedistrictingProgram.md to those found in OldRedistricting.md

**Comment by amitcham1** [comment]
This is a duplicate issues with problem #104, as they both were to improve the greyscale for a printed version of the graphics.

**Comment by Jsatram** [comment]
Windows 10 Home
Dell XPS 13
1920 x 1200 resolution

<img width="390" alt="Greyscalev2" src="https://user-images.githubusercontent.com/50312818/144120524-e3bd4a5d-67e9-48e1-8164-3fcd46d25090.PNG">

**Comment by franciscomuniz** [comment]
Windows 10
1920x1080
HP Pavillionx360 Convertible 15
![Greyscale](https://user-images.githubusercontent.com/91153874/144121391-dfa5ce94-2317-4e6d-8ef9-e874403e9ddf.PNG)

**Comment by krisellecodes** [comment]
![NewfigureA](https://user-images.githubusercontent.com/77947095/144121288-100a21da-24ba-40cd-98c9-405107b58944.png)

macOS Catalina
Macbook Pro
1680 x 1050

**Comment by jody** [comment]
<img width="775" alt="Screen Shot 2021-11-30 at 7 25 13 PM" src="https://user-images.githubusercontent.com/379845/144160664-0dff58b8-9180-49f7-b05b-70b1dc417d06.png">

MacOS Big Sur (11.6.1)

**Comment by jody** [comment]
Thank you for checking this out and verifying that resolution of #104 also resolved this issue!
