### ISSUE TITLE
[User Story] Documentation: Running a Demonstration Prototype

### ISSUE THREAD

**Issue by mykewlker** [MetroCS/redistricting#9]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a _Maintainer_
I want _clear direction on how to run a demonstration prototype_
so that _I can improve my understanding of the project_

## Acceptance Criteria
 - [ ] A document exists in the repository that explains how to run the product that uses language and expectations suitable for maintainers.

## Additional Notes
The document may also contain tips for newcomers on how to run the product, but that may be addressed in a separate document.

**Comment by jody** [comment]
This seems an overly broad definition of the "user" of the product.  Given that there's no documentation of stakeholder types, it can mean anything.  In general, we tend to think of "user" as "end user", which in this case would be someone wanting to "run" the program, not someone wanting to "build" the program.

Until the actual stakeholders are defined, I suggest the outcome of this story better applies to a "maintainer" than a "user".

If the "run" the program rationale is a critical part of the story, then the outcome should be "how to run the program" and "build" should be removed from the rationale.

The acceptance criteria isn't concrete.  What is the definition of "getting started"?  How is that determined?  Likewise, what is the metric for determining "understand"?

Please update this user story.

**Comment by mykewlker** [comment]
Please assign to @FrederickBuker as well

**Comment by mykewlker** [comment]
This user story has been updated to better reflect the needs of a maintainer as well as acceptance criteria better defined

**Comment by mykewlker** [comment]
This story can also be related to [Clustered Readme](https://github.com/MetroCS/redistricting/issues/11) Epic story as Getting Started documentation should be prominently displayed on the Readme

**Comment by jody** [comment]
OK.  (I'm still confused about "additional applications needed to run the project".)

**Comment by TheGerbilvonSteuben** [comment]
Last Minute Software Solutions would like to handle this issue.

**Comment by jody** [comment]
Per GitHub restrictions, I can only assign those who have demonstrated some activity with the issue.  (That is, any member who wishes to be assigned will need to comment directly.)

**Comment by jody** [comment]
Removing RedistrictingDriver from the package is becoming a highly likely outcome. All issues/PRs that address concerns involving RedistrictingDriver are thus likely to be irrelevant. Am putting all such activity "on hold" for now.

**Comment by jody** [comment]
* Addressed by #145
