### ISSUE TITLE
[UserStory] Clarify naming and usage of demonstration prototypes

### ISSUE THREAD

**Issue by jody** [MetroCS/redistricting#90]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _stakeholder (all types)_  
**I want**  _clear documentation of the intents and usages of all demonstration prototypes_  
**so that**  _I can identify such demonstration prototypes and readily glean their intents and usages._

## Acceptance Criteria

* _Demonstration prototypes are readily identified by a well-documented naming convention._
* _Intents and expectations are documented for each demonstration prototype._
* _Usage instructions are documented for each demonstration prototype._

_The only existing demonstration prototype is [RedistrictingDriver](https://github.com/MetroCS/redistricting/blob/master/src/swdmt/redistricting/RedistrictingDriver.java). That class name and its API description are misleading. Once a naming convention has been adopted and documented, that name RedistrictingDriver should be changed and the class comment modified to document the intent, expectations, and usage._

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
_(Issues on which this story depends)_
### Dependents
_(Issues dependent on this story)_

**Comment by jody** [comment]
This needs more consideration.

The terms "prototype" and "demonstration" are used but without clarity of meaning.

An explicit statement of the intention of the **RedistrictingDriver** class would be useful here.

**Comment by BatchOfAllTrades** [comment]
Am I clear in understanding that this issue has two parts?
1. Create a naming convention for the demonstration prototypes.
2. Update the names of demonstration prototypes, expressly "RedistrictingDriver".
Is the maintainer expecting two separate pull requests or one that addresses both issues simultaneously?

**Comment by BatchOfAllTrades** [comment]
Furthermore, does the maintainer have an example of such naming convention in practice that the resolution of this issue can be modeled after?

**Comment by jody** [comment]
> Am I clear in understanding that this issue has two parts?
> 
> 1. Create a naming convention for the demonstration prototypes.
> 2. Update the names of demonstration prototypes, expressly "RedistrictingDriver".

Yes, this appears to involve two distinct issues.
It seems best to split this into two sub-stories:
1. Establishing a naming convention for demonstration prototypes.
2. Renaming the current demonstration prototype as necessary to match the naming convention.

The second issue (renaming) is dependent on resolving the first issue (convention). Resolving this issue (#90) depends on both.

This also clarifies that separate PRs are likely to be effective in responding to the individual issues.

> Furthermore, does the maintainer have an example of such naming convention in practice that the resolution of this issue can be modeled after?

Not at present. Addressing the naming-convention issue involves (a) reviewing the landscape to see if there are any applicable common conventions and (b) suggesting one or more possible conventions for adoption by this project.

**Comment by jody** [comment]
The code that currently exists in [RedistrictingDriver](https://github.com/MetroCS/redistricting/blob/master/src/swdmt/redistricting/RedistrictingDriver.java) is actually an integration test rather than either a demonstration or a prototype of a redistricting application.  The term _integration test_ is used here to encompass verification of behaviors between modules that are themselves subjects of unit-testing.

The existence of the main method in RedistrictingDriver seems to be more confusing and misleading than helpful.
https://github.com/MetroCS/redistricting/blob/e146aca06033eddca11766090d3aef0723f06b64/src/swdmt/redistricting/RedistrictingDriver.java#L32
This is compounded by the interactive aspect of eliciting values from the console.
https://github.com/MetroCS/redistricting/blob/e146aca06033eddca11766090d3aef0723f06b64/src/swdmt/redistricting/RedistrictingDriver.java#L37-L41
https://github.com/MetroCS/redistricting/blob/e146aca06033eddca11766090d3aef0723f06b64/src/swdmt/redistricting/RedistrictingDriver.java#L68-L77

The integration performed by RedistrictingDriver could be wrapped into one or more explicit tests.  Some test verification may be non-automated, that is, specified by particular observations and assessments of human evaluators.  For example, the understandability of textual and graphical-rendering outputs.

**Would appreciate more thoughts on converting RedistrictingDriver into an integration test!**

**Comment by jody** [comment]
Removing RedistrictingDriver from the package is becoming a highly likely outcome. this issie is now the primary issue to be addressed. All other issues/PRs that address concerns involving RedistrictingDriver are thus likely to be irrelevant. Am putting all such activity "on hold" for now.

**Comment by jody** [comment]
* Addressed by #145
