### ISSUE TITLE
[UserStory] Display Redistricting Output in GUI

### ISSUE THREAD

**Issue by JoeSGunter** [MetroCS/redistricting#93]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  stakeholder of any type
**I want**  the program to display the districts in a similar manner as seen [here](https://github.com/MetroCS/redistricting/blob/master/images/NewfigureB.png) and [here.](https://github.com/MetroCS/redistricting/raw/master/images/NewfigureA.png)
**so that**  there is a legible, color coordinated manner to view the program information.

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Rule 1_ The program accurately displays a graphical depiction of the initial region.
* _Rule 2_ The program displays a graphical depiction of a region that accurately shows that region's districts' boundaries.

### Depends On
N/A
### Dependents
Issue #37

**Comment by jody** [comment]
I'm wondering about the use of the term "pop out window".  My best understanding of that term is as applying to an embedded display that is being brought out to its own window.  Is that consistent with the meaning here?  If so, what is the original display that is being "popped out"?

I think the linkage between Acceptance Criterion Rule 1 and Rule 2 is not needed and adds an undesired constraint. Could Rule 2 be stated as the following? "The program displays a graphical depiction of a region that accurately shows that region's districts' boundaries."

**Comment by JoeSGunter** [comment]
@jody updated title and rule 2 to better reflect the intent of this user story

**Comment by jody** [comment]
> updated title

The new title is confusing. Are there _any_ examples in the project's [Wiki](https://github.com/MetroCS/redistricting/wiki)?

**Comment by jody** [comment]
> I want the program to display the districts in a similar manner as seen [here](
![](https://github.com/MetroCS/redistricting/blob/master/images/NewfigureB.png)
) and [here](
![](https://github.com/MetroCS/redistricting/raw/master/images/NewfigureA.png)
).

I note that there's been a problem identified with those particular renderings; see issue #104.

**Comment by jody** [comment]
Incomplete. No response in over 30 days. Closing issue.
